version: '3.8'
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: goodnight_app-postgres
    environment:
      POSTGRES_DB: goodnight_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
    ports:
      - "5432:5432"
    command: "postgres -c 'max_connections=500'"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgres-data:

networks:
  default:
    name: mynetwork

